import { chromium } from '@playwright/test';
const OUT = 'C:/Users/user/AppData/Local/Temp/claude/c--Users-user-Desktop-honeybook/601a47a9-b3f8-4bff-afa7-70fb58c1d361/scratchpad/';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
await p.goto('http://localhost:3000/sign-in');
await p.fill('input[type=email]', 'demo@handled.test');
await p.fill('input[type=password]', 'demo123');
await p.click('button[type=submit]');
await p.waitForURL('**/dashboard', { timeout: 60000 });
await p.goto('http://localhost:3000/clients');
await p.waitForLoadState('networkidle');
const names = () => p.locator('tbody tr td:nth-child(2)').allInnerTexts();
console.log('start :', (await names()).join(', '));
await p.click('thead button:has-text("Name")');
await p.waitForTimeout(1200);
console.log('desc? :', (await names()).join(', '));
await p.click('thead button:has-text("Name")');
await p.waitForTimeout(1200);
console.log('again :', (await names()).join(', '));
await p.click('thead button:has-text("Last interaction")');
await p.waitForTimeout(1500);
console.log('by date:', (await p.locator('tbody tr td:nth-child(6)').allInnerTexts()).join(' | '));
await p.reload();
await p.waitForLoadState('networkidle');
await p.waitForTimeout(1000);
console.log('after reload, sort kept:', (await p.locator('tbody tr td:nth-child(6)').allInnerTexts()).join(' | '));
// table preferences
await p.click('button[aria-label="Table preferences"]');
await p.waitForTimeout(500);
const labels = p.locator('[data-menu] label');
const out = [];
for (let i = 0; i < await labels.count(); i++) {
  const l = labels.nth(i);
  out.push(((await l.locator('input').isChecked()) ? '[x]' : '[ ]') + (await l.innerText()).trim());
}
console.log('PANEL:', out.join(' '));
await p.screenshot({ path: OUT + 'prefs.png' });
await p.locator('[data-menu] label:has-text("Mailing address") input').check();
await p.locator('[data-menu] label:has-text("Website") input').check();
await p.locator('[data-menu] label:has-text("Job title") input').check();
await p.locator('[data-menu] label:has-text("Tags") input').check();
await p.waitForTimeout(1500);
await p.mouse.click(640, 800);
await p.waitForTimeout(300);
console.log('ALL ON:', (await p.locator('thead').innerText()).replace(/\n/g, ' | '));
const hs = await p.locator('thead th').evaluateAll((e) => e.map((x) => Math.round(x.getBoundingClientRect().height)));
console.log('header heights:', hs.join(','));
const box = await p.locator('.card').first().evaluate((e) => ({ scroll: e.scrollWidth, client: e.clientWidth }));
console.log('scrolls sideways:', box.scroll > box.client, box);
await p.screenshot({ path: OUT + 'contacts-all.png' });
await p.locator('.card').first().evaluate((e) => e.scrollTo({ left: 9999 }));
await p.waitForTimeout(400);
await p.locator('tbody tr').first().hover();
await p.waitForTimeout(400);
await p.screenshot({ path: OUT + 'contacts-scrolled.png' });
await b.close();
